#include ../../../Dist/mk/PcapPlusPlus.mk

#All Target
all:
	g++.exe $(PCAPPP_INCLUDES) -O2 -std=c++0x -c -o parser.o parser.cpp
	g++.exe $(PCAPPP_LIBS_DIR) -static-libstdc++ -o parser parser.o $(PCAPPP_LIBS)

clean:
	del parser.o
	del parser

